# Generated by Django 6.0.3 on 2026-04-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
