# Generated by Django 6.0.3 on 2026-04-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approved_days',
            field=models.IntegerField(default=0),
        ),
    ]
